### ISSUE TITLE
[Non-rigid tracking] Sparse tracking with feature descriptors

### ISSUE THREAD

**Issue by steveazzolin** [materight/object_tracking#5]
- [x] Baseline implementation
- [x] Using a mask to extract only the foreground features
- [ ] Outlier detection
- [ ] Non convex-shape
- [ ] Tracking with these features (create a mask of search around the user-defined ROI, extract features at time t and t+1, match the features and create a new ROI as the center of the matched points. Iterate.)
