### ISSUE TITLE
[Non-rigid tracking] Semi-supervised learning

### ISSUE THREAD

**Issue by steveazzolin** [materight/object_tracking#6]
Try for example KNN, KNN with heuristics (4/8 connection), Graph cut, Interactive Image Segmentation, ...
- [x] On the space of RGB values
- [x] On the space of some other features (ORB)
- [x] Normalized cut (https://people.eecs.berkeley.edu/~malik/papers/SM-ncut.pdf)
- [ ] https://docs.opencv.org/master/dc/df6/tutorial_py_histogram_backprojection.html
